package au.com.gaiaresources.bdrs.controller.test;

import au.com.gaiaresources.bdrs.model.taxa.TaxonRank;

public interface TestDataConstants {
    public static final String[] TEST_GROUPS = { "Birds", "Butterflies",
            "Rabbits", "Livestock", "Elephants", "Insects", "Fish",
            "Marine Life", "Deer", "Worms", "Arthropods", "Crocodilians",
            "Spiders", "Ferrets", "Snakes", "Sharks", "Freshwater Mussels",
            "Terrestrial Mammals", "Crocodiles", "Lizards", "Marine Mammals",
            "Marine Mussels", "Arachnids", "Monkeys", "Cats", "Reptiles",
            "Mammals", "Salamanders", "Dogs", "Horses", "Frogs",
            "Freshwater Snails", "Crustaceans", "Tigers", "Amphibians", "Pigs",
            "Vertebrates", "Eagles", "Fishes", "Alligators", "Marine Turtles",
            "Whales", "Echinoderms", "Turtles", "Mollusks", "Fungi",
            "Tortoises", "Bears", "Invertebrates", "Bats",
            "Freshwater Turtles", "Molluscs", "Iguanas" };

    public static final String[] FIRST_NAMES = { "William", "Grace", "Arthur",
            "Jared", "Henry", "Sara", "Billy", "Emma", "Tracy", "Holly",
            "Erin", "Catherine", "Claudia", "Sheila", "Tom", "Tina", "Cody",
            "Milton", "Melissa", "Kelly", "Thomas", "Michael", "Clinton",
            "Todd", "Lucy", "Matthew", "Jamie", "Terry", "Hazel", "Allan",
            "Nathan", "Phillip", "Ivan", "Ashley", "Virgil", "Ella",
            "Francisco", "Bryan", "Marsha", "Viola", "Enrique", "Lucille",
            "Curtis", "Leah", "Jorge", "Roger", "Paula", "Cory", "Troy",
            "Anna", "Kristen", "Tyler", "Janice", "Georgia", "Claire", "Nora",
            "Marjorie", "Eva", "Christina", "Priscilla", "Wendy", "Florence",
            "Shirley", "Dennis", "Pedro", "Christopher", "Ramon", "Joy",
            "Ernest", "Ethel", "Regina", "Geraldine", "Gabriel", "Ted",
            "Daniel", "Stella", "Stephanie", "Adrian", "Harold", "Gregory",
            "Frank", "Terrance", "Paul", "Joseph", "Theodore", "Leonard",
            "Steve", "Dorothy", "Roberto", "Javier", "Nicholas", "Louis",
            "Nicole", "Martha", "Renee", "Jessie", "Andrea", "Leroy", "Max",
            "Pauline", "Craig", "Johnnie", "Felicia", "Philip", "Rhonda",
            "John", "Marilyn", "Sherry", "Laura", "Penny", "Kimberly",
            "Willard", "Brent", "Dwight", "Byron", "Guy", "Dan", "Sean",
            "Stephen", "Kristina", "Marie", "Lawrence", "Tiffany", "Albert",
            "Shelly", "Lester", "Crystal", "Ana", "Robert", "Violet", "Ronnie",
            "Sandra", "Tanya", "Dana", "Christy", "Gordon", "Earl", "Maxine",
            "Brenda", "Constance", "Ben", "Rosemary", "Edwin", "Adam", "Katie",
            "Edith", "Phyllis", "Elmer", "Heather", "Scott", "Annie", "Lois",
            "Kay", "Lydia", "Alvin", "Bernard", "Ruben", "Amber", "Joann",
            "Gene", "Barbara", "Kathy", "Wallace", "Helen", "Corey", "Pamela",
            "Laurie", "Linda", "Debra", "Mabel", "Jennie", "Rene", "Jo",
            "Jeanette", "Erika", "Don", "Wilma", "Sam", "Tim", "Andre",
            "Charlotte", "Julian", "Melanie", "Sally", "Roberta", "Russell",
            "Jerry", "Micheal", "Joan", "Jacob", "Heidi", "Rita", "Misty",
            "Andrew", "Jason", "Sherri", "Allen", "Carrie", "Jimmie", "Jill",
            "Johnny", "Bruce", "Cecil", "Rose", "Joshua", "Nelson", "Lauren",
            "Delores", "Bonnie", "Chad", "Myrtle", "Bessie", "Dianne",
            "Frederick", "Charlene", "Monica", "Randall", "Yolanda", "Clara",
            "Vera", "Jane", "Katrina", "Dale", "Jamie", "Vivian", "Joyce",
            "George", "Josephine", "Justin", "Teresa", "Raul", "Howard",
            "Gilbert", "Shane", "Ryan", "Cynthia", "Jose", "Julia", "Eugene",
            "Floyd", "Leon", "Jean", "Clayton", "Brett", "Elaine", "Alberto",
            "Bernice", "Jeffrey", "Derek", "Maureen", "Lynn", "Mildred",
            "Dean", "Judith", "Billie", "Stacey", "Chris", "Evelyn", "April",
            "Brandon", "Harry", "Joanne", "Manuel", "Carla", "Daisy", "Janet",
            "Diane", "Rick", "Barry", "Irma", "Terri", "Irene", "Mattie",
            "Darren", "Hector", "Karen", "Dave", "Dawn", "Darrell", "Doris",
            "Brian", "Tamara", "Tony", "Margaret", "Douglas", "Claude",
            "Ellen", "Caroline", "Shannon", "Naomi", "Jeffery", "Morris",
            "Arlene", "Darlene", "Jennifer", "Aaron", "James", "Veronica",
            "Samuel", "Donna", "Jaime", "Marshall", "Ron", "Warren", "Dora",
            "Miguel", "Annette", "Sidney", "Clifford", "Alfred", "Maurice",
            "Carl", "Clarence", "Loretta", "Jenny", "Eddie", "Wade", "Luis",
            "Ronald", "Christian", "Raymond", "Karl", "Leo", "Arnold", "Pearl",
            "Agnes", "Lillian", "Gertrude", "Marion", "Sergio", "Margie",
            "Jacqueline", "Roy", "Shawn", "Gerald", "Steven", "Leona", "Brad",
            "Marcus", "Nancy", "Stanley", "Sue", "Jackie", "Kurt", "Ida",
            "Angela", "Antonio", "Lance", "Ross", "Jonathan", "Hugh", "Nellie",
            "Patsy", "Felix", "Ralph", "Clyde", "Rosa", "Kent", "Glenn",
            "Marc", "Sharon", "Kenneth", "Gary", "Daryl", "Brittany", "Betty",
            "Marion", "Cindy", "Ricky", "Bobbie", "Jimmy", "Jeff", "Salvador",
            "Beverly", "Olga", "Patricia", "Leslie", "Emily", "Sylvia",
            "Robin", "Audrey", "Armando", "Cathy", "Ruby", "Jesse", "Sarah",
            "Ken", "Jon", "Ramona", "Patrick", "Valerie", "Yvonne", "Travis",
            "Roland", "Lee", "Amanda", "Minnie", "Willie", "Carmen", "Andy",
            "Tommy", "Bertha", "Peggy", "Beth", "Eric", "Denise", "Thelma",
            "Dolores", "Willie", "Ruth", "Ricardo", "Louise", "Vanessa",
            "Walter", "Kyle", "Mary", "Eileen", "Kelly", "Gladys", "Fernando",
            "Charlie", "Rodney", "Melinda", "Jeanne", "Alexander", "Samantha",
            "Marlene", "Keith", "Martin", "Courtney", "Rachel", "Bradley",
            "Eleanor", "Benjamin", "Juan", "Deanna", "Colleen", "Kevin",
            "Nina", "Julie", "Anne", "Jay", "Edward", "Susan", "Gloria", "Bob",
            "Jesus", "Tara", "Calvin", "Marcia", "Diana", "Velma", "Everett",
            "Alicia", "Terrence", "Dustin", "Herman", "Zachary", "Duane",
            "Marian", "Katherine", "Joel", "Mike", "Oscar", "Danny", "Vincent",
            "Timothy", "Marvin", "Harvey", "Larry", "Jack", "Ann", "Frances",
            "Glen", "Ian", "Tonya", "Hilda", "Richard", "Carol", "Maria",
            "Fred", "Rafael", "Stacy", "Erica", "Natalie", "Cheryl", "Wesley",
            "Edna", "Leslie", "Tracey", "Gwendolyn", "Jessica", "Angel",
            "Suzanne", "Norma", "Vicki", "Esther", "Greg", "Ray", "Brandy",
            "Melvin", "Jessie", "Lillie", "Judy", "Michelle", "Anthony",
            "Jerome", "Kathleen", "Edgar", "Kim", "Michele", "Anita", "Dwayne",
            "Donald", "Mitchell", "Mathew", "Clifton", "Neil", "Julio",
            "Nathaniel", "Allison", "Tracy", "Becky", "Darryl", "Tyrone",
            "Kristin", "Tammy", "Elizabeth", "Alice", "Sonia", "Victoria",
            "Vernon", "Christine", "Gina", "Megan", "Lloyd", "Casey", "Mae",
            "Miriam", "David", "Freddie", "Victor", "Chester", "Glenda", "Jim",
            "Erik", "Debbie", "Alfredo", "Bobby", "Elsie", "Wanda", "Carlos",
            "Toni", "Deborah", "Joe", "Lonnie", "Franklin", "Bill", "Theresa",
            "Lori", "Carole", "Carolyn", "Perry", "Jeremy", "Alan", "Wayne",
            "Juanita", "Mario", "Jordan", "Cassandra", "Virginia", "Terry",
            "Peter", "Connie", "Kathryn", "Isaac", "Kirk", "Charles", "Amy",
            "Lorraine", "June", "Reginald", "Randy", "Norman", "Lewis",
            "Beatrice", "Alex", "Seth", "Lena", "Vickie", "Danielle", "Lisa",
            "Derrick", "Eduardo", "Alma", "Rebecca", "Francis", "Mark",
            "Herbert", "Gail" };

    public static final String[] SURNAMES = { "Smith", "Johnson", "Williams",
            "Jones", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor",
            "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin",
            "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez",
            "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez",
            "King", "Wright", "Lopez", "Hill", "Scott", "Green", "Adams",
            "Baker", "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez",
            "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans",
            "Edwards", "Collins", "Stewart", "Sanchez", "Morris", "Rogers",
            "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey", "Rivera",
            "Cooper", "Richardson", "Cox", "Howard", "Ward", "Torres",
            "Peterson", "Gray", "Ramirez", "James", "Watson", "Brooks",
            "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross",
            "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long",
            "Patterson", "Hughes", "Flores", "Washington", "Butler", "Simmons",
            "Foster", "Gonzales", "Bryant", "Alexander", "Russell", "Griffin",
            "Diaz", "Hayes", "Myers", "Ford", "Hamilton", "Graham", "Sullivan",
            "Wallace", "Woods", "Cole", "West", "Jordan", "Owens", "Reynolds",
            "Fisher", "Ellis", "Harrison", "Gibson", "Mcdonald", "Cruz",
            "Marshall", "Ortiz", "Gomez", "Murray", "Freeman", "Wells", "Webb",
            "Simpson", "Stevens", "Tucker", "Porter", "Hunter", "Hicks",
            "Crawford", "Henry", "Boyd", "Mason", "Morales", "Kennedy",
            "Warren", "Dixon", "Ramos", "Reyes", "Burns", "Gordon", "Shaw",
            "Holmes", "Rice", "Robertson", "Hunt", "Black", "Daniels",
            "Palmer", "Mills", "Nichols", "Grant", "Knight", "Ferguson",
            "Rose", "Stone", "Hawkins", "Dunn", "Perkins", "Hudson", "Spencer",
            "Gardner", "Stephens", "Payne", "Pierce", "Berry", "Matthews",
            "Arnold", "Wagner", "Willis", "Ray", "Watkins", "Olson", "Carroll",
            "Duncan", "Snyder", "Hart", "Cunningham", "Bradley", "Lane",
            "Andrews", "Ruiz", "Harper", "Fox", "Riley", "Armstrong",
            "Carpenter", "Weaver", "Greene", "Lawrence", "Elliott", "Chavez",
            "Sims", "Austin", "Peters", "Kelley", "Franklin", "Lawson",
            "Fields", "Gutierrez", "Ryan", "Schmidt", "Carr", "Vasquez",
            "Castillo", "Wheeler", "Chapman", "Oliver", "Montgomery",
            "Richards", "Williamson", "Johnston", "Banks", "Meyer", "Bishop",
            "Mccoy", "Howell", "Alvarez", "Morrison", "Hansen", "Fernandez",
            "Garza", "Harvey", "Little", "Burton", "Stanley", "Nguyen",
            "George", "Jacobs", "Reid", "Kim", "Fuller", "Lynch", "Dean",
            "Gilbert", "Garrett", "Romero", "Welch", "Larson", "Frazier",
            "Burke", "Hanson", "Day", "Mendoza", "Moreno", "Bowman", "Medina",
            "Fowler", "Brewer", "Hoffman", "Carlson", "Silva", "Pearson",
            "Holland", "Douglas", "Fleming", "Jensen", "Vargas", "Byrd",
            "Davidson", "Hopkins", "May", "Terry", "Herrera", "Wade", "Soto",
            "Walters", "Curtis", "Neal", "Caldwell", "Lowe", "Jennings",
            "Barnett", "Graves", "Jimenez", "Horton", "Shelton", "Barrett",
            "Obrien", "Castro", "Sutton", "Gregory", "Mckinney", "Lucas",
            "Miles", "Craig", "Rodriquez", "Chambers", "Holt", "Lambert",
            "Fletcher", "Watts", "Bates", "Hale", "Rhodes", "Pena", "Beck",
            "Newman" };

    public static final String[] LATIN_WORDS = { "Mauris", "Diam", "Phasellus",
            "Feugiat", "Pulvinar", "Non", "Tincidunt", "Scelerisque",
            "Ullamcorper", "Inceptos", "Donec", "Malesuada", "Ipsum", "Neque",
            "Posuere", "Habitant", "Egestas", "Lacinia", "Morbi", "Senectus",
            "Velit", "Fames", "Felis", "Pharetra", "Ultrices", "Odio",
            "Nostra", "Faucibus", "Enim", "Rhoncus", "Sodales", "Ligula",
            "Iaculis", "Praesent", "Quis", "Tristique", "Interdum", "Netus",
            "Nec", "Volutpat", "Mattis", "Vitae", "Luctus", "Himenaeos",
            "Elementum", "Gravida", "Congue", "Leo", "Quam", "Euismod",
            "Magna", "Curabitur", "Class", "Porttitor", "Aliquam", "Tortor",
            "Ut", "Litora", "Mi", "Sociosqu", "Dolor", "Nulla", "Laoreet",
            "Semper", "Blandit", "Erat", "Venenatis", "Eu", "Et", "Molestie",
            "Dui", "Pretium", "Fringilla", "Consectetur", "Conubia", "Vel",
            "Mollis", "Metus", "Arcu", "Suscipit", "Aptent", "Cras", "Turpis",
            "Cursus", "Condimentum", "Integer", "Maecenas", "Amet", "Aenean",
            "Vestibulum", "Dapibus", "Torquent", "Viverra", "Ultricies", "Ac",
            "Augue", "Tempor", "Vulputate", "Adipiscing", "Per", "Placerat",
            "Nam", "Ad", "Suspendisse", "Elit", "Sed", "Vivamus", "Ante",
            "Sem", "Nunc", "Eros", "Est", "Sit", "Risus", "Convallis",
            "Tellus", "Quisque", "Etiam", "Massa", "Imperdiet", "Dignissim",
            "Sapien", "Commodo", "Eget", "Hendrerit", "Vehicula", "Tempus",
            "Nibh", "Taciti", "Bibendum", "Fusce", "Aliquet", "Lorem",
            "Accumsan", "A", "Nisi", "Nisl", "Sollicitudin", "Justo", "Libero",
            "Eleifend", "Orci", "Porta", "Fermentum", "Proin", "Varius",
            "Dictum", "Lacus", "Auctor", "Sagittis", "Ornare", "Lectus",
            "Purus", "Duis", "Pellentesque", "At", "In", "Id", "Urna", "Nullam" };

    public static final String[] APPEARANCE_ADJECTIVES = { "Yellow Bellied",
            "Brown", "Pink Spotted", "White Striped", "Blue Tailed", "Black",
            "Green Footed", "Red Nosed", "Orange Spotted", "Purple",
            "Gray Fur", "Gold", "Silver Tongued", "Navy Coloured", "Mottled",
            "Common", "Laughing", "Adorable", "Adventurous", "Aggressive",
            "Alert", "Attractive", "Average", "Beautiful", "Blue-Eyed",
            "Bloody", "Blushing", "Bright", "Clean", "Clear", "Cloudy",
            "Colorful", "Crowded", "Cute", "Dark", "Drab", "Distinct", "Dull",
            "Elegant", "Excited", "Fancy", "Filthy", "Glamorous", "Gleaming",
            "Gorgeous", "Graceful", "Grotesque", "Handsome", "Homely", "Light",
            "Long", "Magnificent", "Misty", "Motionless", "Muddy",
            "Old-Fashioned", "Plain", "Poised", "Precious", "Quaint", "Shiny",
            "Smoggy", "Sparkling", "Spotless", "Stormy", "Strange", "Ugly",
            "Ugliest", "Unsightly", "Unusual", "Wide-Eyed" };

    public static final String TEST_DATA_IMAGE_DIR = "test.data.image.dir";

    public static final int DEFAULT_MIN_IMAGE_WIDTH = 640;
    public static final int DEFAULT_MIN_IMAGE_HEIGHT = 480;

    public static final int DEFAULT_MAX_IMAGE_WIDTH = 1024;
    public static final int DEFAULT_MAX_IMAGE_HEIGHT = 768;

    public static final int MIN_WORDS_IN_SENTENCE = 7;
    public static final int MAX_WORDS_IN_SENTENCE = 15;

    public static final TaxonRank[] TAXON_RANKS = { TaxonRank.KINGDOM,
            TaxonRank.PHYLUM, TaxonRank.CLASS, TaxonRank.ORDER,
            TaxonRank.FAMILY, TaxonRank.GENUS, TaxonRank.SPECIES };

}
