//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.15 at 04:45:32 PM WST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.com.gaiaresources.bdrs.kml.oasis.names.tc.ciq.xsdschema.xal;
